---
title: "all_enloc_phenotype"
author: "joshjiang"
date: "8/13/2019"
output: html_document
---

```{r setup,include=FALSE}
library(ggplot2)
library(tidyverse)
library(gridExtra)
```

```{r,warning=FALSE,message=FALSE}
dapg_file_pattern <- "/Users/joshjiang/hakylab/gtex-gwas-analysis/data/dapg_selected_variants/expression/gwas_and_eqtl/DAPG_with_mashr__{tissue}.rds"
phenotype_lst <- readLines("/Users/joshjiang/hakylab/gtex-gwas-analysis/data/phenotype_list.txt")
metadata <- read_tsv("/Users/joshjiang/hakylab/gtex-gwas-analysis/data/gwas_metadata.txt") %>% rename(phenotype=Tag)
df_master <- read_tsv("/Users/joshjiang/hakylab/gtex-gwas-analysis/data/coloc_enloc_gene_joined.txt")

for (phenotype in phenotype_lst)
{
  df <- df_master[df_master$phenotype==phenotype,]
  short_phenotype <- as.character(metadata[metadata$phenotype==phenotype, "new_Phenotype"])
  
  plot_title <- "All Tissues - {gsub(pattern='_', replacement=' ', x=short_phenotype)} - Enloc\nPrimary vs. secondary eQTL" %>% glue::glue()
  
  pp <- ggplot(df, aes(rank1, rank2))
  pp <- pp + geom_point(alpha=.2, size=4)
  pp <- pp + theme_bw(base_size=20)
  pp <- pp + geom_abline(slope=1,intercept=0)
  pp <- pp + stat_density2d(color = alpha(colour="red",alpha=0.6), contour = TRUE)
  pp <- pp + ggtitle(plot_title) + theme(plot.title = element_text(size = 10))
  pp <- pp + xlab(expression(beta[prim])) + ylab(expression(beta[sec]))
  pp <- pp + coord_fixed(ratio=1, xlim=c(-3,3), ylim=c(-3,3))
  
  print(pp)
}
```

